import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import icons from "../icons.js";
import { useState } from "react";

const iconStyles = [
  "apple-music",
  "facetime_old",
  "settings",
  "files_style",
  "dev",
  "App Store",
  "Calculator",
  "Clock",
  "FaceTime",
  "iBook",
];

const Icon = (props: { src: string; alt: string }) => {
  return (
    <div className="flex w-1/4 justify-center">
      <div className="p-2">
        <a
          href={props.src}
          download
          className="flex shadow-md h-16 lg:h-24 w-16 lg:w-24 rounded-2xl lg:rounded-3xl overflow-hidden"
        >
          <Image height={100} width={100} src={props.src} alt={props.alt} />
        </a>
      </div>
    </div>
  );
};

const Card = (props: { src: string; alt: string; onClick: () => void }) => (
  <div className="flex w-1/4" onClick={props.onClick}>
    <div className="flex justify-center items-center m-2 w-full h-20 hover:bg-gray-100 rounded border border-gray-200 cursor-pointer">
      <Image height={32} width={32} src={props.src} alt={props.alt} />
    </div>
  </div>
);

const Home: NextPage = () => {
  const [query, setQuery] = useState("");
  const [selectedIcon, setSelectedIcon] = useState(icons[0]);

  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/output.css" rel="stylesheet"></link>
      </Head>

      <div className="bg-blue-400 w-full">
        <div className="container mx-auto py-4 px-2">
          <h1 className="text-lg font-bold text-white">App Icons</h1>
        </div>
      </div>

      <div className="border mb-4">
        <div className="container mx-auto">
          <input
            placeholder="Search..."
            className="w-full h-12 px-2 focus:outline-0"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
        </div>
      </div>

      <div className="container mx-auto flex flex-col lg:flex-row h-full">
        <div className="flex flex-row flex-wrap w-full lg:w-1/2 overflow-scroll">
          {icons
            .filter((icon) => icon.includes(query))
            .map((icon, index) => (
              <Card
                key={index}
                src={`/assets/rounded/${icon}.svg`}
                alt={icon}
                onClick={() => setSelectedIcon(icon)}
              />
            ))}
        </div>

        <div className="flex flex-row flex-wrap content-start w-full lg:w-1/2 h-full">
          {iconStyles.map((style, index) => (
            <Icon
              key={index}
              src={`/assets/${style}/${selectedIcon}.png`}
              alt={selectedIcon}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
