const iconStyles = [
  {
    enabled: true,
    name: "Red",
    path: "red",
    color: "#DC6F6F",
    gradient: ["#DC6F6F", "#DA5C5C"],
  },
  {
    enabled: false,
    name: "Orange",
    path: "orange",
    color: "#ED8B6F",
    gradient: ["#ED8B6F", "#EB7A5B"],
  },
  {
    enabled: false,
    name: "Light Orange",
    path: "light_orange",
    color: "#E8A960",
    gradient: ["#E8A960", "#E49C4C"],
  },
  {
    enabled: false,
    name: "Yellow",
    path: "yellow",
    color: "#E1C341",
    gradient: ["#E1C341", "#DDBC33"],
  },
  {
    enabled: false,
    name: "Green",
    path: "green",
    color: "#65C068",
    gradient: ["#65C068", "#56B453"],
  },
  {
    enabled: true,
    name: "Aqua",
    path: "aqua",
    color: "#53C7AD",
    gradient: ["#53C7AD", "#27BFA1"],
  },
  {
    enabled: false,
    name: "Sky Blue",
    path: "sky_blue",
    color: "#56C4D6",
    gradient: ["#56C4D6", "#3BBBD0"],
  },
  {
    enabled: true,
    name: "Blue",
    path: "blue",
    color: "#4DAEEA",
    gradient: ["#4DAEEA", "#34A0E3"],
  },
  {
    enabled: false,
    name: "Purple",
    path: "purple",
    color: "#5267B7",
    gradient: ["#5267B7", "#3951AD"],
  },
  {
    enabled: false,
    name: "Violet",
    path: "violet",
    color: "#7F5BB3",
    gradient: ["#7F5BB3", "#6C43A8"],
  },
  {
    enabled: false,
    name: "Dark Pink",
    path: "dark_pink",
    color: "#AB7AD5",
    gradient: ["#AB7AD5", "#9C65CB"],
  },
  {
    enabled: false,
    name: "Pink",
    path: "pink",
    color: "#DD89C8",
    gradient: ["#DD89C8", "#D678BE"],
  },
  {
    enabled: false,
    name: "Gray",
    path: "gray",
    color: "#8A929A",
    gradient: ["#8A929A", "#78808A"],
  },
  {
    enabled: false,
    name: "Green Gray",
    path: "green_gray",
    color: "#959F95",
    gradient: ["#959F95", "#848F84"],
  },
  {
    enabled: false,
    name: "Brown Gray",
    path: "brown_gray",
    color: "#9B928D",
    gradient: ["#9B928D", "#8B817C"],
  },
];

export default iconStyles;